name: Build and Publish Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: eed-web-application/elog-plus-frontend-deployment/.github/workflows/create-image.yml@main
    secrets: inherit
